### Solve it (Gaussian Elemination Method)

$$ 
2x_1 + 3x_2 − x_3 + 4x_4 + x_5 = 10  \\
x_1 − 2x_2 + 3x_3 + x_4 − 2x_5 = 53 \\
x_1 + x_2 + 2x_3 − x_4 + x_5 = 124 \\
x_1 − x_2 + x_3 + 2x_4 + 3x_5 = 85 \\
x_1 + 2x_2 − 3x_3 + x_4 − x_5 = 15 \\
$$

In [11]:
import numpy as np

In [12]:
A = np.array([[2,3,-1,4,1],[1,-2,3,1,-2],[1,1,2,-1,1],[1,-1,1,2,3],[1,2,-3,1,-1]])
C = np.array([[10],[53],[124],[85],[15]])

In [13]:
n = len(A)

def gauss_elemination():
    for i in range(n):
        pivot = A[i][i]
        
        for j in range(i+1, n):
            factor = A[j, i]/pivot
            A[j] = A[j] - factor * A[i]
    
    print(A)

In [14]:
gauss_elemination()

[[  2   3  -1   4   1]
 [  0  -3   3  -1  -2]
 [  0   0   2  -3   0]
 [  0   0   0  -1   3]
 [  0   0   0   0 -13]]


In [15]:
def back_substitution():
    A_upper = gauss_elemination()
    A